description:
  Generate temporary Cloudsmith credentials using OIDC
parameters:
  repository:
    description: The identity/slug of the Cloudsmith repository
    type: string
steps:
  - run:
      name: Cloudsmith - Configure defaults
      command: <<include(scripts/configure_cloudsmith_defaults.sh)>>
  - cloudsmith-oidc/authenticate_with_oidc
  - run:
      name: Cloudsmith - Set environment variables
      command: <<include(scripts/set_env_vars_for_maven.sh)>>
      environment:
        CLOUDSMITH_REPOSITORY: <<parameters.repository>>
  - run:
      name: Cloudsmith - Configure cloudsmith maven
      command: <<include(scripts/configure_maven.sh)>>
      environment:
        CLOUDSMITH_REPOSITORY: <<parameters.repository>>
  - run:
      name: Cloudsmith - Configure settings.xml file for maven
      command: <<include(scripts/generate_settings_file.sh)>>
      environment:
        CLOUDSMITH_REPOSITORY: <<parameters.repository>>