description: >
  Configure maven and install dependencies via the Cloudsmith upstream proxy.
usage:
  version: 2.1
  orbs:
    cloudsmith-maven: ft-circleci-orbs/cloudsmith-maven@1.0
  jobs:
    build:
      docker:
        - image: cimg/openjdk:21.0.2
      steps:
        - checkout
        - cloudsmith-maven/configure_maven:
            repository: "your-repository-id"
        - run:
          name: Install package dependencies
          command: mvn install
          working_directory: ~/project/.circleci/simple-maven-package-test/maven-package-test
  workflows:
    main:
      jobs:
        - build
